export default [
  // ── RS101  Rocket Propulsion ──────────────────────────────────────────────
  {
    _id: "Q101",
    title: "Rocket Propulsion Fundamentals",
    description: "Covers Newton's laws, thrust, and specific impulse.",
    course: "RS101",
    createdBy: "123",
    quizType: "Graded Quiz",
    assignmentGroup: "Quizzes",
    points: 8,
    shuffleAnswers: true,
    timeLimit: 20,
    multipleAttempts: false,
    howManyAttempts: 1,
    showCorrectAnswers: "Immediately",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: new Date("2023-05-10T23:59:00Z"),
    availableDate: new Date("2023-05-01T00:00:00Z"),
    untilDate: new Date("2023-05-11T23:59:00Z"),
    published: true,
    numberOfQuestions: 3,
  },
  {
    _id: "Q102",
    title: "Combustion and Nozzle Design",
    description: "Combustion processes, instability, and de Laval nozzles.",
    course: "RS101",
    createdBy: "123",
    quizType: "Graded Quiz",
    assignmentGroup: "Quizzes",
    points: 8,
    shuffleAnswers: true,
    timeLimit: 20,
    multipleAttempts: true,
    howManyAttempts: 2,
    showCorrectAnswers: "After Due Date",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: new Date("2023-05-17T23:59:00Z"),
    availableDate: new Date("2023-05-08T00:00:00Z"),
    untilDate: new Date("2023-05-18T23:59:00Z"),
    published: true,
    numberOfQuestions: 3,
  },

  // ── RS102  Aerodynamics ───────────────────────────────────────────────────
  {
    _id: "Q201",
    title: "Aerodynamics Fundamentals",
    description: "Lift, drag, Bernoulli's principle, and airfoil basics.",
    course: "RS102",
    createdBy: "123",
    quizType: "Graded Quiz",
    assignmentGroup: "Quizzes",
    points: 8,
    shuffleAnswers: true,
    timeLimit: 15,
    multipleAttempts: false,
    howManyAttempts: 1,
    showCorrectAnswers: "Immediately",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: new Date("2023-05-11T23:59:00Z"),
    availableDate: new Date("2023-05-02T00:00:00Z"),
    untilDate: new Date("2023-05-12T23:59:00Z"),
    published: true,
    numberOfQuestions: 3,
  },
  {
    _id: "Q202",
    title: "Subsonic and Supersonic Flow",
    description: "Mach number, shock waves, and transonic phenomena.",
    course: "RS102",
    createdBy: "123",
    quizType: "Graded Quiz",
    assignmentGroup: "Quizzes",
    points: 8,
    shuffleAnswers: false,
    timeLimit: 20,
    multipleAttempts: false,
    howManyAttempts: 1,
    showCorrectAnswers: "Immediately",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: new Date("2023-05-18T23:59:00Z"),
    availableDate: new Date("2023-05-09T00:00:00Z"),
    untilDate: new Date("2023-05-19T23:59:00Z"),
    published: true,
    numberOfQuestions: 3,
  },

  // ── RS103  Spacecraft Design ──────────────────────────────────────────────
  {
    _id: "Q301",
    title: "Spacecraft Structural Design",
    description: "Materials selection, load-bearing design, and structural analysis.",
    course: "RS103",
    createdBy: "123",
    quizType: "Graded Quiz",
    assignmentGroup: "Quizzes",
    points: 8,
    shuffleAnswers: true,
    timeLimit: 20,
    multipleAttempts: false,
    howManyAttempts: 1,
    showCorrectAnswers: "Immediately",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: new Date("2023-05-12T23:59:00Z"),
    availableDate: new Date("2023-05-03T00:00:00Z"),
    untilDate: new Date("2023-05-13T23:59:00Z"),
    published: true,
    numberOfQuestions: 3,
  },
  {
    _id: "Q302",
    title: "Orbital Mechanics",
    description: "Kepler's laws, orbital transfers, and delta-v calculations.",
    course: "RS103",
    createdBy: "123",
    quizType: "Graded Quiz",
    assignmentGroup: "Quizzes",
    points: 8,
    shuffleAnswers: true,
    timeLimit: 25,
    multipleAttempts: true,
    howManyAttempts: 2,
    showCorrectAnswers: "After Due Date",
    accessCode: "",
    oneQuestionAtATime: false,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: new Date("2023-05-19T23:59:00Z"),
    availableDate: new Date("2023-05-10T00:00:00Z"),
    untilDate: new Date("2023-05-20T23:59:00Z"),
    published: true,
    numberOfQuestions: 3,
  },

  // ── RS104  Organic Chemistry ──────────────────────────────────────────────
  {
    _id: "Q401",
    title: "Functional Groups and Reactions",
    description: "Identification of functional groups and reaction types.",
    course: "RS104",
    createdBy: "123",
    quizType: "Graded Quiz",
    assignmentGroup: "Quizzes",
    points: 8,
    shuffleAnswers: true,
    timeLimit: 20,
    multipleAttempts: false,
    howManyAttempts: 1,
    showCorrectAnswers: "Immediately",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: new Date("2023-05-13T23:59:00Z"),
    availableDate: new Date("2023-05-04T00:00:00Z"),
    untilDate: new Date("2023-05-14T23:59:00Z"),
    published: true,
    numberOfQuestions: 3,
  },
  {
    _id: "Q402",
    title: "Stereochemistry and Spectroscopy",
    description: "Enantiomers, IR spectroscopy, and NMR fundamentals.",
    course: "RS104",
    createdBy: "123",
    quizType: "Graded Quiz",
    assignmentGroup: "Quizzes",
    points: 8,
    shuffleAnswers: false,
    timeLimit: 20,
    multipleAttempts: false,
    howManyAttempts: 1,
    showCorrectAnswers: "Immediately",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: new Date("2023-05-20T23:59:00Z"),
    availableDate: new Date("2023-05-11T00:00:00Z"),
    untilDate: new Date("2023-05-21T23:59:00Z"),
    published: false,
    numberOfQuestions: 3,
  },

  // ── RS105  Inorganic Chemistry ────────────────────────────────────────────
  {
    _id: "Q501",
    title: "Coordination Chemistry",
    description: "Ligands, chelation, and coordination number.",
    course: "RS105",
    createdBy: "123",
    quizType: "Graded Quiz",
    assignmentGroup: "Quizzes",
    points: 8,
    shuffleAnswers: true,
    timeLimit: 20,
    multipleAttempts: false,
    howManyAttempts: 1,
    showCorrectAnswers: "Immediately",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: new Date("2023-05-14T23:59:00Z"),
    availableDate: new Date("2023-05-05T00:00:00Z"),
    untilDate: new Date("2023-05-15T23:59:00Z"),
    published: true,
    numberOfQuestions: 3,
  },
  {
    _id: "Q502",
    title: "Crystal Field Theory",
    description: "d-orbital splitting, high-spin vs. low-spin complexes.",
    course: "RS105",
    createdBy: "123",
    quizType: "Practice Quiz",
    assignmentGroup: "Quizzes",
    points: 8,
    shuffleAnswers: true,
    timeLimit: 15,
    multipleAttempts: true,
    howManyAttempts: 3,
    showCorrectAnswers: "Immediately",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: new Date("2023-05-21T23:59:00Z"),
    availableDate: new Date("2023-05-12T00:00:00Z"),
    untilDate: new Date("2023-05-22T23:59:00Z"),
    published: true,
    numberOfQuestions: 3,
  },

  // ── RS106  Physical Chemistry ─────────────────────────────────────────────
  {
    _id: "Q601",
    title: "Thermodynamics",
    description: "Gibbs free energy, entropy, and spontaneity.",
    course: "RS106",
    createdBy: "123",
    quizType: "Graded Quiz",
    assignmentGroup: "Exams",
    points: 8,
    shuffleAnswers: false,
    timeLimit: 30,
    multipleAttempts: false,
    howManyAttempts: 1,
    showCorrectAnswers: "After Due Date",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: true,
    lockQuestionsAfterAnswering: true,
    dueDate: new Date("2023-05-15T23:59:00Z"),
    availableDate: new Date("2023-05-06T00:00:00Z"),
    untilDate: new Date("2023-05-16T23:59:00Z"),
    published: true,
    numberOfQuestions: 3,
  },
  {
    _id: "Q602",
    title: "Kinetics and Quantum Chemistry",
    description: "Arrhenius equation, reaction rates, and wave mechanics.",
    course: "RS106",
    createdBy: "123",
    quizType: "Graded Quiz",
    assignmentGroup: "Quizzes",
    points: 8,
    shuffleAnswers: true,
    timeLimit: 20,
    multipleAttempts: false,
    howManyAttempts: 1,
    showCorrectAnswers: "Immediately",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: new Date("2023-05-22T23:59:00Z"),
    availableDate: new Date("2023-05-13T00:00:00Z"),
    untilDate: new Date("2023-05-23T23:59:00Z"),
    published: true,
    numberOfQuestions: 3,
  },

  // ── RS107  Ancient Languages of Middle-earth ──────────────────────────────
  {
    _id: "Q701",
    title: "Elvish Languages Quiz",
    description: "Quenya vs. Sindarin — history, usage, and script.",
    course: "RS107",
    createdBy: "678",
    quizType: "Graded Quiz",
    assignmentGroup: "Quizzes",
    points: 8,
    shuffleAnswers: true,
    timeLimit: 20,
    multipleAttempts: false,
    howManyAttempts: 1,
    showCorrectAnswers: "Immediately",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: new Date("2023-05-09T23:59:00Z"),
    availableDate: new Date("2023-05-01T00:00:00Z"),
    untilDate: new Date("2023-05-10T23:59:00Z"),
    published: true,
    numberOfQuestions: 3,
  },
  {
    _id: "Q702",
    title: "Dwarvish and the Black Speech",
    description: "Khuzdul, its secrecy, and the One Ring inscription.",
    course: "RS107",
    createdBy: "678",
    quizType: "Graded Quiz",
    assignmentGroup: "Quizzes",
    points: 8,
    shuffleAnswers: false,
    timeLimit: 15,
    multipleAttempts: false,
    howManyAttempts: 1,
    showCorrectAnswers: "Immediately",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: new Date("2023-05-16T23:59:00Z"),
    availableDate: new Date("2023-05-08T00:00:00Z"),
    untilDate: new Date("2023-05-17T23:59:00Z"),
    published: true,
    numberOfQuestions: 3,
  },

  // ── RS108  Inter-species Diplomacy ────────────────────────────────────────
  {
    _id: "Q801",
    title: "Alliances and Councils of Middle-earth",
    description: "The Council of Elrond, White Council, and key alliances.",
    course: "RS108",
    createdBy: "678",
    quizType: "Graded Quiz",
    assignmentGroup: "Quizzes",
    points: 8,
    shuffleAnswers: true,
    timeLimit: 20,
    multipleAttempts: false,
    howManyAttempts: 1,
    showCorrectAnswers: "Immediately",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: new Date("2023-05-11T23:59:00Z"),
    availableDate: new Date("2023-05-02T00:00:00Z"),
    untilDate: new Date("2023-05-12T23:59:00Z"),
    published: true,
    numberOfQuestions: 3,
  },
  {
    _id: "Q802",
    title: "Conflicts and Resolutions",
    description: "Battle of Five Armies, War of the Ring, and Aragorn's unification.",
    course: "RS108",
    createdBy: "678",
    quizType: "Graded Quiz",
    assignmentGroup: "Quizzes",
    points: 8,
    shuffleAnswers: true,
    timeLimit: 20,
    multipleAttempts: true,
    howManyAttempts: 2,
    showCorrectAnswers: "After Due Date",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    dueDate: new Date("2023-05-18T23:59:00Z"),
    availableDate: new Date("2023-05-09T00:00:00Z"),
    untilDate: new Date("2023-05-19T23:59:00Z"),
    published: true,
    numberOfQuestions: 3,
  },
];
